/**
 * Mentora AI - Primary Education Script (Arabic)
 * Contains interactive game logic for Primary grade children.
 * Optimized for touch devices and Arabic (RTL).
 */

// ==========================================
// CENTRAL CHECK FUNCTION
// ==========================================

function checkActivity(type, id) {
  switch (type) {
    case 'memory':
      // Memory games are usually auto-validated, but if a manual check is needed:
      showFeedback(`feedback-${id}`, true, "أحسنت! استمر في اللعب.");
      break;
    case 'dragdrop':
      checkDragDrop(id);
      break;
    case 'sorting':
      checkSorting(id);
      break;
    case 'drawing':
      // Drawing is subjective, usually just 'Bravo' for participation
      showFeedback(`feedback-${id}`, true, "رسم جميل! أحسنت.");
      break;
    case 'quiz':
      validateVraiFaux(id);
      break;
    case 'linking':
        checkLinking(id);
        break;
    default:
      console.warn("Unknown activity type:", type);
  }
}

function resetActivity(id) {
    // Try to find a specific reset function based on the specialized initialization
    // For now, simple forceful reload of inner HTML or class removal
    const container = document.getElementById(id);
    if(!container) return;
    
    // Clear feedback
    const feedback = document.getElementById(`feedback-${id}`);
    if(feedback) feedback.style.display = 'none';

    // Drag Drop Reset
    const draggables = container.querySelectorAll('.draggable-item');
    const zones = container.querySelectorAll('.drop-zone');
    if(draggables.length > 0 && zones.length > 0) {
        // Return items to original container (assuming there is a source-container)
        const source = container.querySelector('.source-container');
        if(source) {
            draggables.forEach(d => {
                source.appendChild(d);
                d.classList.remove('correct', 'wrong');
            });
            zones.forEach(z => {
                z.classList.remove('occupied', 'correct', 'wrong');
            });
        }
    }

    // Memory Reset
    const cards = container.querySelectorAll('.memory-card');
    if(cards.length > 0) {
        cards.forEach(c => {
            c.classList.remove('flipped', 'matched');
        });
        // Shuffle again?
        // simple shuffle
        const grid = container.querySelector('.memory-grid');
        for (let i = grid.children.length; i >= 0; i--) {
            grid.appendChild(grid.children[Math.random() * i | 0]);
        }
    }

    // Linking Reset (Canvas)
    const canvas = container.querySelectorAll('canvas');
    if(canvas.length > 0){
        // Clear canvas
         // If we stored the linking instance, we need to reset it.
         // This is tricky without object storage.
         // We will rely on re-init or just clearRect.
         // For simplistic implementation:
        //  initLinkingGame(id); // Re-init if possible or just clear
    }

    // Default QCM Reset
    const options = container.querySelectorAll('.qcm-option');
    options.forEach(o => {
        o.classList.remove('selected', 'feedback-success', 'feedback-error');
    });
}


// ==========================================
// MEMORY GAME
// ==========================================
/*
Expected HTML Structure:
<div id="game1" class="activity-container memory-game">
  <div class="memory-grid">
     <!-- Cards generated by JS or static -->
     <div class="memory-card" data-val="1">...front/back...</div>
     <div class="memory-card" data-val="1">...</div>
  </div>
</div>
*/

function initMemoryGame(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;
  
  const cards = Array.from(container.querySelectorAll('.memory-card'));
  let hasFlippedCard = false;
  let lockBoard = false;
  let firstCard, secondCard;
  let matches = 0;
  const totalPairs = cards.length / 2;

  function flipCard() {
    if (lockBoard) return;
    if (this === firstCard) return;

    this.classList.add('flipped');

    if (!hasFlippedCard) {
      hasFlippedCard = true;
      firstCard = this;
      return;
    }

    secondCard = this;
    checkForMatch();
  }

  function checkForMatch() {
    let isMatch = firstCard.dataset.val === secondCard.dataset.val;
    isMatch ? disableCards() : unflipCards();
  }

  function disableCards() {
    firstCard.removeEventListener('click', flipCard);
    secondCard.removeEventListener('click', flipCard);
    firstCard.classList.add('matched');
    secondCard.classList.add('matched');
    resetBoard();
    matches++;
    if(matches === totalPairs) {
        showFeedback(`feedback-${containerId}`, true, "ممتاز! لقد وجدت جميع الأزواج.");
    }
  }

  function unflipCards() {
    lockBoard = true;
    setTimeout(() => {
      firstCard.classList.remove('flipped');
      secondCard.classList.remove('flipped');
      resetBoard();
    }, 1000);
  }

  function resetBoard() {
    [hasFlippedCard, lockBoard] = [false, false];
    [firstCard, secondCard] = [null, null];
  }

  // Shuffle
  const grid = container.querySelector('.memory-grid');
  if(grid) {
      cards.forEach(card => {
        let randomPos = Math.floor(Math.random() * cards.length);
        card.style.order = randomPos;
        card.addEventListener('click', flipCard);
      });
  }
}


// ==========================================
// DRAG AND DROP
// ==========================================
/*
Expected Structure:
<div id="dd1" class="drag-drop-container">
   <div class="source-container">
      <div class="draggable-item" draggable="true" data-target="zone1">Item</div>
   </div>
   <div class="target-container">
      <div class="drop-zone" data-zone="zone1">Zone 1</div>
   </div>
</div>
*/

function initDragDrop(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;

    const draggables = container.querySelectorAll('.draggable-item');
    const droppables = container.querySelectorAll('.drop-zone');

    draggables.forEach(draggable => {
        draggable.addEventListener('dragstart', () => {
            draggable.classList.add('dragging');
        });

        draggable.addEventListener('dragend', () => {
            draggable.classList.remove('dragging');
        });
        
        // Touch support for mobile
        draggable.addEventListener('touchstart', handleTouchStart, {passive: false});
        draggable.addEventListener('touchmove', handleTouchMove, {passive: false});
        draggable.addEventListener('touchend', handleTouchEnd);
    });

    droppables.forEach(zone => {
        zone.addEventListener('dragover', e => {
            e.preventDefault();
            zone.classList.add('drag-over');
        });
        
        zone.addEventListener('dragleave', () => {
             zone.classList.remove('drag-over');
        });

        zone.addEventListener('drop', e => {
            e.preventDefault();
            zone.classList.remove('drag-over');
            const draggable = container.querySelector('.dragging');
            if(draggable) {
                zone.appendChild(draggable);
            }
        });
    });

    // Simple Touch Logic (Fallback)
    let activeTouchElement = null;
    let touchOffsetX = 0;
    let touchOffsetY = 0;
    let originalParent = null;

    function handleTouchStart(e) {
        activeTouchElement = e.target.closest('.draggable-item');
        if(!activeTouchElement) return;
        e.preventDefault(); // prevent scrolling
        const touch = e.touches[0];
        const rect = activeTouchElement.getBoundingClientRect();
        touchOffsetX = touch.clientX - rect.left;
        touchOffsetY = touch.clientY - rect.top;
        originalParent = activeTouchElement.parentElement;
        
        activeTouchElement.style.position = 'absolute';
        activeTouchElement.style.zIndex = 1000;
        activeTouchElement.style.width = rect.width + 'px';
        activeTouchElement.classList.add('dragging');
        
        document.body.appendChild(activeTouchElement); // Move to body to float over everything
        moveElement(touch.clientX, touch.clientY);
    }

    function handleTouchMove(e) {
        if(!activeTouchElement) return;
        e.preventDefault();
        const touch = e.touches[0];
        moveElement(touch.clientX, touch.clientY);
    }

    function moveElement(x, y) {
        activeTouchElement.style.left = (x - touchOffsetX) + 'px';
        activeTouchElement.style.top = (y - touchOffsetY) + 'px';
    }

    function handleTouchEnd(e) {
        if(!activeTouchElement) return;
        activeTouchElement.classList.remove('dragging');
        activeTouchElement.style.position = '';
        activeTouchElement.style.zIndex = '';
        activeTouchElement.style.width = '';
        activeTouchElement.style.left = '';
        activeTouchElement.style.top = '';

        // Check drop
        const touch = e.changedTouches[0];
        activeTouchElement.style.display = 'none'; // hide to find element below
        let elemBelow = document.elementFromPoint(touch.clientX, touch.clientY);
        activeTouchElement.style.display = '';

        const dropZone = elemBelow ? elemBelow.closest('.drop-zone') : null;
        
        if(dropZone && container.contains(dropZone)) {
            dropZone.appendChild(activeTouchElement);
        } else {
            originalParent.appendChild(activeTouchElement); // return to start
        }
        activeTouchElement = null;
    }
}

function checkDragDrop(containerId) {
    const container = document.getElementById(containerId);
    let correctCount = 0;
    let totalItems = 0;

    const zones = container.querySelectorAll('.drop-zone');
    zones.forEach(zone => {
        const expected = zone.dataset.zone;
        const items = zone.querySelectorAll('.draggable-item');
        
        items.forEach(item => {
            totalItems++;
            if(item.dataset.target === expected) {
                correctCount++;
                item.classList.add('correct');
            } else {
                item.classList.add('wrong');
            }
        });
    });
    
    // Also count unplaced items if they should be placed? 
    // Usually all items should be distributed.
    // Let's assume total items is ALL items in the container.
    const allItems = container.querySelectorAll('.draggable-item').length;
    
    // If items are left in source, they are incomplete or wrong? 
    // Let's stick to what's placed.
    
    if (correctCount === allItems && allItems > 0) {
        showFeedback(`feedback-${containerId}`, true, "عمل رائع! كل العناصر في مكانها الصحيح.");
    } else {
        showFeedback(`feedback-${containerId}`, false, "هناك بعض الأخطاء، حاول مرة أخرى.");
    }
}


// ==========================================
// SORTING GAME
// ==========================================
// Lists that need to be reordered
// Using jquery-ui sortable style or simple up/down buttons?
// Native Drag/Drop sort is complex for touch without lib.
// Let's implement simple "Click to select, Click to swap" or Up/Down arrows.
// Up/Down arrows are easiest for accessibility and simple impl.

function initSorting(containerId) {
    const list = document.querySelector(`#${containerId} .sortable-list`);
    if(!list) return;
    
    // Add controls to each item if not present
    const items = list.querySelectorAll('li');
    items.forEach(item => {
        if(!item.querySelector('.sort-controls')) {
            const controls = document.createElement('div');
            controls.className = 'sort-controls';
            controls.innerHTML = `
                <button class="up-btn">▲</button>
                <button class="down-btn">▼</button>
            `;
            item.appendChild(controls);
            
            controls.querySelector('.up-btn').onclick = () => {
                const prev = item.previousElementSibling;
                if(prev) list.insertBefore(item, prev);
            };
            controls.querySelector('.down-btn').onclick = () => {
                const next = item.nextElementSibling;
                if(next) list.insertBefore(next, item);
            };
        }
    });
}

function checkSorting(containerId) {
    const list = document.querySelector(`#${containerId} .sortable-list`);
    const items = list.querySelectorAll('li');
    let isCorrect = true;
    
    items.forEach((item, index) => {
        if(parseInt(item.dataset.order) !== index + 1) {
            isCorrect = false;
            item.classList.add('wrong');
        } else {
            item.classList.remove('wrong');
            item.classList.add('correct');
        }
    });
    
    showFeedback(`feedback-${containerId}`, isCorrect, isCorrect ? "ترتيب صحيح! ممتاز." : "الترتيب غير صحيح.");
}

// ==========================================
// LINKING GAME (Canvas)
// ==========================================
/*
 Structure:
 <div id="link1" class="linking-container">
    <canvas id="canvas-link1" width="400" height="300"></canvas>
    <div class="col-left">
       <div class="link-node" data-id="1" style="top: 20px">A</div>
       ...
    </div>
    <div class="col-right">
       <div class="link-node" data-match="1" style="top: 50px">B</div>
       ...
    </div>
 </div>
 DO NOT USE CANVAS only. Overlay divs are better for text.
 The script will draw lines on the canvas behind the divs.
*/

let currentLinks = {}; // Store links per game id

function initLinkingGame(containerId) {
    const container = document.getElementById(containerId);
    if (!container) return;
    const canvas = container.querySelector('canvas');
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    let selectedNode = null;
    let lines = []; // {start: {x,y, id}, end: {x,y, id}}
    currentLinks[containerId] = lines;
    
    const nodes = container.querySelectorAll('.link-node');
    
    function draw() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        
        // Style settings
        ctx.lineWidth = 3;
        ctx.lineCap = 'round';
        
        lines.forEach(line => {
             ctx.strokeStyle = '#4CAF50';
             ctx.beginPath();
             ctx.moveTo(line.start.x, line.start.y);
             ctx.lineTo(line.end.x, line.end.y);
             ctx.stroke();
        });
        
        if (selectedNode) {
             // Optional: Draw line to mouse cursor? (Skip for simplicity)
        }
    }
    
    nodes.forEach(node => {
        node.addEventListener('click', () => {
             const rect = node.getBoundingClientRect();
             const canvasRect = canvas.getBoundingClientRect();
             
             // Calculate center relative to canvas
             // Note: in RTL, X might need adjustment? 
             // Canvas coordinates are always Top-Left based standard.
             const x = (rect.left + rect.width/2) - canvasRect.left;
             const y = (rect.top + rect.height/2) - canvasRect.top;
             
             if (!selectedNode) {
                 selectedNode = {x, y, id: node.dataset.id, side: node.parentElement.className, element: node};
                 node.classList.add('selected');
             } else {
                 if (selectedNode.element === node) {
                     // Deselect
                     selectedNode = null;
                     node.classList.remove('selected');
                 } else if (selectedNode.side === node.parentElement.className) {
                     // Same side switch
                     selectedNode.element.classList.remove('selected');
                     selectedNode = {x, y, id: node.dataset.id, side: node.parentElement.className, element: node};
                     node.classList.add('selected');
                 } else {
                     // Create Link
                     // Remove existing links for these nodes
                     lines = lines.filter(l => l.start.element !== selectedNode.element && l.end.element !== node);
                     lines = lines.filter(l => l.start.element !== node && l.end.element !== selectedNode.element);
                     
                     lines.push({
                         start: selectedNode,
                         end: {x, y, id: node.dataset.id, element: node}
                     });
                     
                     selectedNode.element.classList.remove('selected');
                     selectedNode = null;
                     currentLinks[containerId] = lines;
                     draw();
                 }
             }
        });
    });
    
    // Resize observer to redraw if layout changes?
    // For now, assume static layout.
}

function checkLinking(containerId) {
    const lines = currentLinks[containerId] || [];
    let correct = 0;
    // We expect nodes to have data-id and data-match
    // Left side: data-id="X". Right side: data-match="X".
    
    lines.forEach(line => {
        const startEl = line.start.element;
        const endEl = line.end.element;
        
        // Find which is which
        const id1 = startEl.dataset.id || startEl.dataset.match;
        const id2 = endEl.dataset.id || endEl.dataset.match;
        
        // Check if they match. 
        // We need a robust way.
        // Convention: Left items have data-val="A", Right items have data-val="A".
        if(startEl.dataset.val === endEl.dataset.val) {
            correct++;
        }
    });

    const totalPairs = document.querySelectorAll(`#${containerId} .col-left .link-node`).length;
    
    if(correct === totalPairs && lines.length === totalPairs) {
        showFeedback(`feedback-${containerId}`, true, "أحسنت! كل التوصيلات صحيحة.");
    } else {
        showFeedback(`feedback-${containerId}`, false, "حاول مرة أخرى، هناك أخطاء.");
    }
}
